"""added password field

Revision ID: 42961e34d82b
Revises: 0e053225c3c2
Create Date: 2024-03-27 01:55:23.581617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42961e34d82b'
down_revision = '0e053225c3c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
