"""added a foreign key

Revision ID: 682608639d75
Revises: dedb3e66015f
Create Date: 2024-03-28 19:47:09.027932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682608639d75'
down_revision = 'dedb3e66015f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('offer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk', 'users', ['offer_id'], ['id'])
        batch_op.drop_column('shopowner')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shopowner', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('offer_id')

    # ### end Alembic commands ###
